pipeline {
    agent any
    environment {
        IMAGE_NAME = "prajwal1903/travel-booking-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Prajwal1903/travel-booking-app.git'
            }
        }
        stage('Build') {
            steps {
                dir('travel-booking-app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('travel-booking-app') {
                    sh 'mvn test'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('travel-booking-app') {
                    sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                        credentialsId: 'docker',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
                    docker push $IMAGE_NAME:$IMAGE_TAG
                    docker push $IMAGE_NAME:latest
                    '''
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                dir('travel-booking-app') {
                    sh 'ansible-playbook ansible/deploy.yml'
                }
            }
        }
    }
    post {
        success { echo 'Pipeline executed successfully.' }
        failure { echo 'Pipeline failed.' }
    }
}
